"""empty message

Revision ID: 1590fde0b71f
Revises: 85cabae3ee33
Create Date: 2021-04-13 17:06:56.685161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1590fde0b71f'
down_revision = '85cabae3ee33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_tasks', sa.Column('comment', sa.Text(), nullable=True))
    op.alter_column('tbl_tasks', 'task_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_tasks', 'task_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('tbl_tasks', 'comment')
    # ### end Alembic commands ###
