"""empty message

Revision ID: 2029924e1fbb
Revises: be29302e054b
Create Date: 2021-04-12 15:56:06.976154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2029924e1fbb'
down_revision = 'be29302e054b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_tasks', sa.Column('end_time', sa.Date(), nullable=True))
    op.create_index(op.f('ix_tbl_tasks_end_time'), 'tbl_tasks', ['end_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_tasks_end_time'), table_name='tbl_tasks')
    op.drop_column('tbl_tasks', 'end_time')
    # ### end Alembic commands ###
