"""empty message

Revision ID: be29302e054b
Revises: 6db8279b1d52
Create Date: 2021-04-12 13:33:35.550059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be29302e054b'
down_revision = '6db8279b1d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ds_token_black_list', ['id'])
    op.create_unique_constraint(None, 'tbl_auth_service_users', ['id'])
    op.create_unique_constraint(None, 'tbl_auth_service_verify_code', ['id'])
    op.create_unique_constraint(None, 'tbl_role', ['id'])
    op.create_unique_constraint(None, 'tbl_tasks', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_tasks', type_='unique')
    op.drop_constraint(None, 'tbl_role', type_='unique')
    op.drop_constraint(None, 'tbl_auth_service_verify_code', type_='unique')
    op.drop_constraint(None, 'tbl_auth_service_users', type_='unique')
    op.drop_constraint(None, 'ds_token_black_list', type_='unique')
    # ### end Alembic commands ###
